### ISSUE TITLE
[Feature Request] Download all chapters at once

### ISSUE THREAD

**Issue by koopa1338** [josueBarretogit/manga-tui#9]
Downloading mangas with many chapters is currently time-consuming. A shortcut to download all chapters would be very nice.

**Comment by koopa1338** [comment]
Besides that, there might be a bug when downloading multiple chapters. Currently, it is only possible to change pages in the chapter overview when there are no current downloads on that page.

**Comment by josueBarretogit** [comment]
Yes you are right I was thinking about this but the mangadex api has some rate limits, that may be an issue with mangas like one piece, but for most  mangas this should not be a problem, at the moment I'm working on this pull request #8  after that this issue goes next

**Comment by josueBarretogit** [comment]
@koopa1338 if you have rust installed you can checkout the branch `download-all-chapters-at-once` and compile since this functionality is already done but will take a while to be integrated, when you are on a manga page press `a` and then follow the instructions

https://github.com/user-attachments/assets/27738dcf-5771-4e32-b81a-89db4cabdd14

**Comment by koopa1338** [comment]
very nice, appreciate this feature. I will test this thoroughly and report my findings :heart:
